name: 'Cypress Screenshot & Video Upload to Slack'
branding:
  icon: file
  color: blue
description: 'After running a Cypress test in a Github action, upload the screenshots and videos directly to Slack'
inputs:
  token:
    description: 'Slack token'
    required: true
  channel:
    description: 'Slack channel'
    required: true
  screenshotsDir:
    description: 'The path of the directory where Cypress stores its screenshots. Defaults to `cypress/screenshots`. No trailing slashes, please.'
    required: false
  videosDir:
    description: 'The path of the directory where Cypress stores its videos. Defaults to `cypress/videos`. No trailing slashes, please.'
    required: false
  message-text:
    description: 'Custom Slack message text'
    required: false
  uploadType:
    description: 'What to upload: "both" (default), "screenshots", or "videos"'
    required: false
    default: 'both'
outputs:
  result:
    description: 'Result of video and screenshot uploads'
runs:
  using: 'node20'
  main: 'dist/main.js'
